name: zephyr-transit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - seaborn
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - nbval
  - pip:
    - ruff
    - pre-commit