"""added unique constraints to station, observation, station_variable

Revision ID: 6055c9a20750
Revises: 854387812710
Create Date: 2025-07-10 13:30:21.966984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6055c9a20750'
down_revision: Union[str, None] = '854387812710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_observation', 'observations', ['station_id', 'variable_id', 'time'])
    op.create_unique_constraint('unique_station_variable', 'station_variables', ['station_id', 'variable_id'])
    op.create_unique_constraint('unique_station_per_source', 'stations', ['source_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_station_per_source', 'stations', type_='unique')
    op.drop_constraint('unique_station_variable', 'station_variables', type_='unique')
    op.drop_constraint('unique_observation', 'observations', type_='unique')
    # ### end Alembic commands ###
